### ISSUE TITLE
Pulse Modulation Continuously Per Device or Per Channel

### ISSUE THREAD

**Issue by OzHawk** [christian-hahn/windfreak-python#1]
Is the "pulse_mod_enable" flag settable for each channel, or only for the whole device?

The implementation in synth_hd.py indicates that it is per device.

**Comment by christian-hahn** [comment]
Hi OzHawk,

Please excuse the stupendously late response.  I performed a small experiment and confirmed that the "pulse_mod_enable" is settable PER device, not per channel.

```python
# Read 'pulse_cont' with each channel selected
dut.write('channel', 0)
dut.read('pulse_cont')  -->  False
dut.write('channel', 1)
dut.read('pulse_cont') -->  False

# Set 'pulse_cont' while channel 0 was selected
dut.write('channel', 0)
dut.write('pulse_cont', 1)
dut.read('pulse_cont') -->  True
dut.write('channel', 1)
dut.read('pulse_cont') -->  True

# Clear 'pulse_cont' while channel 1 was selected
dut.write('pulse_cont', 0)
dut.read('pulse_cont') -->  False
dut.write('channel', 0)
dut.read('pulse_cont') -->  False
```
I vaguely recall performing a similar experiment on all state within the device when first writing the driver, since the documentation is not explicit on this point.

Thanks,
Christian

**Comment by OzHawk** [comment]
Thanks Christian.  I was in touch with David some time ago, and he confirmed that it is per device also.
